defmodule ExpoEscom.Repo.Migrations.AddCurrentResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:eventos, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :nombre, :text, null: false
      add :descripcion, :text, null: false
      add :ano, :bigint, null: false
      add :color_fondo, :text, null: false
      add :url_cartel, :text, null: false
    end

    create table(:equipos, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :nombre, :text, null: false
      add :asignatura, :text, null: false
      add :puntaje, :bigint
    end

    create table(:docentes, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :es_jurado, :boolean
      add :turno, :text
      add :departamento_id, :bigint
      add :academia_id, :bigint
    end

    create table(:departamentos, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:docentes) do
      modify :departamento_id,
             references(:departamentos,
               column: :id,
               name: "docentes_departamento_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:departamentos) do
      add :nombre, :text, null: false
    end

    create table(:carreras, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :nombre, :text, null: false
    end

    create table(:alumnos, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :numero_boleta, :text, null: false

      add :carrera_id,
          references(:carreras,
            column: :id,
            name: "alumnos_carrera_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :equipo_id,
          references(:equipos,
            column: :id,
            name: "alumnos_equipo_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create table(:actividades, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :nombre, :text, null: false
      add :comienza_en, :utc_datetime
      add :url_cartel, :text
      add :tipo, :text
      add :premio, :text
      add :url_evaluacion, :text

      add :evento_id,
          references(:eventos,
            column: :id,
            name: "actividades_evento_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create table(:academias, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:docentes) do
      modify :academia_id,
             references(:academias,
               column: :id,
               name: "docentes_academia_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:academias) do
      add :nombre, :text, null: false
    end
  end

  def down do
    alter table(:academias) do
      remove :nombre
    end

    drop constraint(:docentes, "docentes_academia_id_fkey")

    alter table(:docentes) do
      modify :academia_id, :bigint
    end

    drop table(:academias)

    drop constraint(:actividades, "actividades_evento_id_fkey")

    drop table(:actividades)

    drop constraint(:alumnos, "alumnos_carrera_id_fkey")

    drop constraint(:alumnos, "alumnos_equipo_id_fkey")

    drop table(:alumnos)

    drop table(:carreras)

    alter table(:departamentos) do
      remove :nombre
    end

    drop constraint(:docentes, "docentes_departamento_id_fkey")

    alter table(:docentes) do
      modify :departamento_id, :bigint
    end

    drop table(:departamentos)

    drop table(:docentes)

    drop table(:equipos)

    drop table(:eventos)
  end
end
