defmodule ExpoEscom.Repo.Migrations.AddPoliciesAndRefactorRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :nombres, :text, null: false
      add :apellido_paterno, :text, null: false
      add :rol, :text, null: false
      add :estado, :text, null: false
    end

    alter table(:equipos) do
      add :actividad_id,
          references(:actividades,
            column: :id,
            name: "equipos_actividad_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :docente_id,
          references(:docentes,
            column: :id,
            name: "equipos_docente_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    alter table(:docentes) do
      remove :departamento_id

      add :user_id,
          references(:users,
            column: :id,
            name: "docentes_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:alumnos) do
      add :user_id,
          references(:users,
            column: :id,
            name: "alumnos_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:actividades) do
      add :academia_id,
          references(:academias,
            column: :id,
            name: "actividades_academia_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :docente_id,
          references(:docentes,
            column: :id,
            name: "actividades_docente_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    alter table(:academias) do
      add :departamento_id,
          references(:departamentos,
            column: :id,
            name: "academias_departamento_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:academias, "academias_departamento_id_fkey")

    alter table(:academias) do
      remove :departamento_id
    end

    drop constraint(:actividades, "actividades_academia_id_fkey")

    drop constraint(:actividades, "actividades_docente_id_fkey")

    alter table(:actividades) do
      remove :docente_id
      remove :academia_id
    end

    drop constraint(:alumnos, "alumnos_user_id_fkey")

    alter table(:alumnos) do
      remove :user_id
    end

    drop constraint(:docentes, "docentes_user_id_fkey")

    alter table(:docentes) do
      remove :user_id

      add :departamento_id,
          references(:departamentos,
            column: :id,
            name: "docentes_departamento_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    drop constraint(:equipos, "equipos_actividad_id_fkey")

    drop constraint(:equipos, "equipos_docente_id_fkey")

    alter table(:equipos) do
      remove :docente_id
      remove :actividad_id
    end

    alter table(:users) do
      remove :estado
      remove :rol
      remove :apellido_paterno
      remove :nombres
    end
  end
end
